### ISSUE TITLE
debt: commited tarteaucitronjs lib

### ISSUE THREAD

**Issue by douglasduteil** [SocialGouv/onvs#134]
Why not using [tarteaucitronjs](https://www.npmjs.com/package/tarteaucitronjs) from npm ?

**Comment by pom421** [comment]
Ni leur site, ni la doc officielle ne parle de l'installation via npm donc j'ai pas osé. 
Si vous n'avez pas constaté de pb, je prends note pour la prochaine fois, ça sera mieux effectivement.

Ceci étant, on n'a plus de cookie, je dois le supprimer.

**Comment by pom421** [comment]
Code removed in 2.15.0.
