### ISSUE TITLE
[Numericité] MAJ bandeau cookies

### ISSUE THREAD

**Issue by Laura-LBC** [SocialGouv/onvs#94]
Bonjour à l'équipe,

On fait suite aux informations données récemment sur les démarches à suivre pour la conformité sur les cookies.

Pour ONVS, il faudrait rajouter Matomo dans le bandeau cookies. 

Bonne journée!
Laura (Numericité)

**Comment by OMoukoko** [comment]
Hello l'équipe,

Pour faire suite au message de Laura à propos du bandeau Cookies, nous vous rappelons qu'Hotjar est un outil américain qui collecte et transfère des informations aux Etats-Unis. Dans le cadre d'une mise en conformité et d'une pratique exemplaire de la Fabrique, nous souhaitons le retrait d'Hotjar parmi les cookies utilisés par Medlé.

Nous restons à votre disposition pour répondre à toute autre question.

Très cordialement,
Osiris Moukoko Priso
