### ISSUE TITLE
Site et mise à jour des documents relatifs à la conformité

### ISSUE THREAD

**Issue by OMoukoko** [SocialGouv/onvs#97]
Hello l'équipe,

Nous passons en revue les sites des produits de la Fabrique dans le cadre de la mise en conformité et nous avons plusieurs remarques sur les documents de conformité mis en ligne :

- La Politique de confidentialité n'est pas en ligne. Elle se trouve dans le dossier RGPD du Nextcloud de la Fabrique, dans le sous-dossier "ONVS".
<img width="1405" alt="Capture d’écran 2021-02-23 à 15 31 46" src="https://user-images.githubusercontent.com/79263610/108858296-4973f580-75ec-11eb-80b3-b673c137f1cf.png">

- Les mentions légales ont été confondues avec les conditions générales d'utilisation. Elles se trouvent également dans le dossier RGPD du Nextcloud de la Fabrique, dans le sous-dossier "ONVS".
<img width="1407" alt="Capture d’écran 2021-02-23 à 15 32 56" src="https://user-images.githubusercontent.com/79263610/108858452-74f6e000-75ec-11eb-912e-3bdd6bf8468b.png">

- Les CGU doivent également être mise en forme de manière plus lisible (il conviendrait d'espacer un peu les articles et parties) car il pourrait nous être reproché de présenter une information illisible. 

- Nous vous rappelons également qu'une mise à jour de la fiche registre est également attendue par Thomas Honnet pour s'assurer d'une conformité à l'instant T. 

A votre disposition pour répondre à vos questions,

Très cordialement,
Osiris Moukoko Priso

**Comment by pom421** [comment]
Rebonjour, 

Comme pour Médlé, on va pouvoir se passer du bandeau de consentement des cookies (pas de cookies à part Matomo à terme, et Hothar à supprimer).

Donc ce que j'ai mis comme Mentions légales, devrait s'appeler CGU et il faut ajouter un lien qui pointe aussi vers les mentions légales, tout ça dans le pied de page du site. Ai-je bien compris @OMoukoko ?

Qu'appelles-tu une fiche registre ? As-tu connaissance de ça @saniyaas ?

**Comment by OMoukoko** [comment]
Bonjour @pom421 ,

Effectivement, dès la suppression de Hotjar, vous pourrez vous passez de bandeau.

Oui, exactement, il faut pointer trois liens pour être plus précis : 
- un sur les mentions légales ;
- un sur les conditions d'utilisation (vers lesquelles pointent aujourd'hui vos mentions légales) ;
- un sur la politique de confidentialité.

Les trois doivent être dans le pied de page du site.

Pour ce qui est de la fiche registre ou fiche de traitement, il s'agit d'un document Excel que vous avez déjà rempli, mais dont nous voudrions la dernière version, ou au alors un message à Thomas précisant qu'il n'y a pas de modification. 

Très cordialement

**Comment by pom421** [comment]
Done.
